source 'http://rubygems.org'

gem 'rails'

gem 'sqlite3', :require => 'sqlite3'

gem 'authlogic'
gem 'deltacloud-client', :require => 'deltacloud'
gem 'sass'
gem 'haml'
gem 'will_paginate'
gem 'nokogiri'
gem 'compass'
gem 'compass-960-plugin', :require => 'ninesixty'
gem 'simple-navigation'
gem 'typhoeus'
gem 'rest-client'
#gem 'rack-restful_submit'
gem 'uuidtools'
gem 'pg'
gem 'thin'
gem 'json'
gem 'railties'
gem 'rspec'
