#!/bin/bash
#
#
# deltacloud-core       startup script for deltacloud-core server
#
# chkconfig: - 97 03
# description: deltacloud-core is primary server process for the \
#    Deltacloud Core component.
#

[ -r /etc/sysconfig/deltacloud-<%= name %> ] && . /etc/sysconfig/deltacloud-<%= name %>

ENV="${ENV:-production}"
DRIVER="${DRIVER:-<%= provider_type %>}"
PORT="${PORT:-<%= port %>}"
LOCKFILE="${LOCKFILE:-/var/lock/subsys/deltacloud-$DRIVER }"
LOGFILE="${LOGFILE:-/var/log/deltacloud-<%= name %>/$DRIVER.log}"
export DELTACLOUD_MOCK_STORAGE=/usr/lib/ruby/gems/1.8/gems/deltacloud-<%= name %>-0.2.0/lib/deltacloud/drivers/mock/data/

PROG=/usr/bin/deltacloudd

. /etc/init.d/functions

start() {
    echo -n "Starting deltacloud-<%= name %>: "

    $PROG -i $DRIVER -e $ENV -p $PORT >> $LOGFILE 2>&1 &
    RETVAL=$?
    if [ $RETVAL -eq 0 ] && touch $LOCKFILE ; then
      echo_success
      echo
    else
      echo_failure
      echo
    fi
}

stop() {
    echo -n "Shutting down deltacloud-<%= name %>: "
    RETVAL=$?
    # FIXME! we need to do a killproc -p <pidfile> here to ensure other deltacloud
    # daemons are not killed as well
    killall deltacloudd
    if [ $RETVAL -eq 0 ] && rm -f $LOCKFILE ; then
      echo_success
      echo
    else
      echo_failure
      echo
    fi
}

case "$1" in
    start)
      start
      ;;
    stop)
      stop
      ;;
    restart)
      stop
      start
      ;;
    reload)
      ;;
    force-reload)
      restart
      ;;
    status)
      status $PROG
      RETVAL=$?
      ;;
    *)
      echo "Usage: deltacloud-<%= name %> {start|stop|restart|status}"
      exit 1
  ;;
esac

exit $RETVAL
