#!/bin/bash
#
#
# deltacloud-core       startup script for deltacloud-core server
#
# chkconfig: - 97 03
# description: deltacloud-core is primary server process for the \
#    Deltacloud Core component.
#

[ -r /etc/sysconfig/deltacloud-<%= name %> ] && . /etc/sysconfig/deltacloud-<%= name %>

ENV="${ENV:-production}"
DRIVER="${DRIVER:-<%= provider_type %>}"
PORT="${PORT:-<%= port %>}"
LOCKFILE="${LOCKFILE:-/var/lock/subsys/deltacloud-<%= name %> }"
LOGFILE="${LOGFILE:-/var/log/deltacloud-<%= name %>/$DRIVER.log}"
PIDFILE="${THIN_PID:-/var/run/deltacloud-<%= name %>.pid}"
export DELTACLOUD_MOCK_STORAGE=/usr/lib/ruby/gems/1.8/gems/deltacloud-<%= name %>-0.2.0/lib/deltacloud/drivers/mock/data/

PROG=/usr/bin/deltacloudd

STARTTIMEOUT=20

. /etc/init.d/functions

start() {
    echo -n "Starting deltacloud-<%= name %>: "

  if [ -f $LOCKFILE ] || [ -f $PIDFILE ] && checkpid `cat $PIDFILE` ; then
    echo_success
    echo
    echo "deltacloud-$DRIVER has already been started"
    exit 0
  fi

  $PROG -i $DRIVER -e $ENV -p $PORT >> $LOGFILE 2>&1 &
  RETVAL=$?
  echo $! > $PIDFILE
  if [ $RETVAL -eq 0 ] ; then
    TIMEOUT="$STARTTIMEOUT"
	  while [ $TIMEOUT -gt 0 ]; do
      /usr/bin/curl --silent http://localhost:$PORT/api >& /dev/null
      RETVAL=$?
      if [ $RETVAL -eq 0 ] ; then
        touch $LOCKFILE
        echo_success
        echo
        exit 0
      fi
      sleep 1
      let TIMEOUT=${TIMEOUT}-1
    done
  fi

  echo_failure
  echo
  exit 1
}

stop() {
    echo -n "Shutting down deltacloud-<%= name %>: "

    # FIXME! we need to do a killproc -p <pidfile> here to ensure other deltacloud
    # daemons are not killed as well
    killproc -p $PIDFILE deltacloudd
    RETVAL=$?
    if [ $RETVAL -eq 0 ] && rm -f $LOCKFILE ; then
      echo_success
      echo
    else
      echo_failure
      echo
    fi
}

case "$1" in
    start)
      start
      ;;
    stop)
      stop
      ;;
    restart)
      stop
      start
      ;;
    reload)
      ;;
    force-reload)
      restart
      ;;
    status)
      status -p $PIDFILE $PROG
      RETVAL=$?
      ;;
    *)
      echo "Usage: deltacloud-<%= name %> {start|stop|restart|status}"
      exit 1
  ;;
esac

exit $RETVAL
