#   Copyright 2011 Red Hat, Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Read conductor settings values from /etc/aeolus-conductor/settings.yml and create facts
# for them. The file is generated by aeolus-conductor rpm.

require 'rubygems'
require 'yaml'

yaml = YAML.load_file("/etc/aeolus-conductor/settings.yml") or raise "Could not open file\n\r"

Facter.add("conductor_settings_session_timeout") do
  setcode do
    yaml[:session][:timeout]
  end
end
